#!/bin/bash

#Keyring
eval $(gnome-keyring-daemon --start --components=ssh)
export SSH_AUTH_SOCK

# Natural scrolling
# Click on touchpad
xinput set-prop 11 353 1
xinput --set-prop 11 376 1

# zxhkd
pgrep -x sxhkd >/dev/null || sxhkd -c ~/.config/sxhkd/sxhkdrc &

# Monitors
external_monitor=$(xrandr --listactivemonitors | tail -n +2 | awk -F' ' '{ print $4 }' | grep -P '^(?!eDP-1).*$' | head -n 1)

if [[ -z ${external_monitor} ]]; then
  bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9 0 &
fi

~/.config/bspwm/monitor_setup.sh --reload

pkill dunst
dunst -conf ~/.config/dunst/dunstrc &

pkill picom
picom &

pkill nm-applet
nm-applet &

pkill blueman-applet
blueman-applet &

bspc config remove_disabled_monitors true

bspc config border_width 2
bspc config normal_border_color "#FFFFFF"
bspc config focused_border_color "#6B8EAE"

bspc config window_gap 10
bspc config pointer_follows_monitor true

# bspc config split_ratio 0.6

# bspc config top_padding 40

bspc rule -a Pieces_for_x state=tiled

bspc rule -a Polybar border=off state=floating layer=above
